east:
  - team1: Duke
    seed1: 1
    team2: American
    seed2: 16
  - team1: Miss St.
    seed1: 8
    team2: Baylor
    seed2: 9
  - team1: Oregon
    seed1: 5
    team2: Liberty
    seed2: 12
  - team1: Arizona
    seed1: 4
    team2: Akron
    seed2: 13
  - team1: BYU
    seed1: 6
    team2: VCU
    seed2: 11
  - team1: Wisconsin
    seed1: 3
    team2: Montana
    seed2: 14
  - team1: Saint Mary's
    seed1: 7
    team2: Vanderbilt
    seed2: 10
  - team1: Alabama
    seed1: 2
    team2: Robert Morris
    seed2: 15
midwest:
  - team1: Houston
    seed1: 1
    team2: SIUE
    seed2: 16
  - team1: Gonzaga
    seed1: 8
    team2: Georgia
    seed2: 9
  - team1: Clemson
    seed1: 5
    team2: McNeese
    seed2: 12
  - team1: Purdue
    seed1: 4
    team2: High Point
    seed2: 13
  - team1: Illinois
    seed1: 6
    team2: Texas
    seed2: 11
  - team1: Kentucky
    seed1: 3
    team2: Troy
    seed2: 14
  - team1: UCLA
    seed1: 7
    team2: Utah St.
    seed2: 10
  - team1: Tennessee
    seed1: 2
    team2: Wofford
    seed2: 15
west:
  - team1: Florida
    seed1: 1
    team2: Norfolk St.
    seed2: 16
  - team1: Uconn
    seed1: 8
    team2: Oklahoma
    seed2: 9
  - team1: Memphis
    seed1: 5
    team2: Colorado St.
    seed2: 12
  - team1: Maryland
    seed1: 4
    team2: Grand Canyon
    seed2: 13
  - team1: Missouri
    seed1: 6
    team2: Drake
    seed2: 11
  - team1: Texas Tech
    seed1: 3
    team2: UNCW
    seed2: 14
  - team1: Kansas
    seed1: 7
    team2: Arkansas
    seed2: 10
  - team1: St. John's
    seed1: 2
    team2: Omaha
    seed2: 15
south:
  - team1: Auburn
    seed1: 1
    team2: Alabama St.
    seed2: 16
  - team1: Louisville
    seed1: 8
    team2: Creighton
    seed2: 9
  - team1: Michigan
    seed1: 5
    team2: UC San Diego
    seed2: 12
  - team1: Texas A&M
    seed1: 4
    team2: Yale
    seed2: 13
  - team1: Ole Miss
    seed1: 6
    team2: San Diego St.
    seed2: 11
  - team1: Iowa St.
    seed1: 3
    team2: Lipscomb
    seed2: 14
  - team1: Marquette
    seed1: 7
    team2: New Mexico
    seed2: 10
  - team1: Michigan
    seed1: 2
    team2: Bryant
    seed2: 15